version: 0.2

env:
  variables:
    DOCKER_IMAGE: "my-frontend"
    DEPLOY_ENV: "production"
  secrets-manager:
    GITHUB_TOKEN: "github-credentials:token"
    GITHUB_USERNAME: "github-credentials:username"

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - git config --global user.email "simon_yau@hotmail.com.hk"
      - git config --global user.name "$GITHUB_USERNAME"
      - git fetch --tags
      - "LATEST_TAG=$(git tag -l | sort -V | tail -n1 || echo 'v0.0.0')"
      - "echo Latest tag found $LATEST_TAG"
      - "IFS='.' read -r MAJOR MINOR PATCH <<< \"${LATEST_TAG#v}\""
      - "NEW_PATCH=$((PATCH + 1))"
      - "NEW_TAG=\"v$MAJOR.$MINOR.$NEW_PATCH\""
      - "echo \"New tag will be $NEW_TAG\""
      - "git tag \"$NEW_TAG\""
      - "git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO} \"$NEW_TAG\""
      - "echo \"{\\\"version\\\": \\\"$NEW_TAG\\\"}\" > src/version.json"
      - "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"


  build:
    commands:
      # Build Docker image
      - docker build --build-arg env=$DEPLOY_ENV -t $DOCKER_IMAGE .
      - docker tag $DOCKER_IMAGE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_IMAGE:$NEW_TAG
      - docker tag $DOCKER_IMAGE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_IMAGE:latest

  post_build:
    commands:
         # Push Docker images to ECR
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_IMAGE:$NEW_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_IMAGE:latest
     
cache:
  paths:
    - '/root/.docker/**/*' 